/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package DIU.VISTA;

import CUI.CONTROLADOR.PersonaControlador;
//import DUI.MODELO.Persona;
import DUI.MODELO.PersonaModelo;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pablo
 */
public class GestorLibros extends javax.swing.JInternalFrame {
ArrayList<PersonaModelo> listaLibroModelo = new ArrayList<>();
    DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Creates new form GestorLibros
     */
    public GestorLibros() {
        initComponents();
        setModelo();
    }

    public void setModelo() {
        String[] cabecera = {"Nro ","título","autor",
            "ISBN", 
            "Páginas","Edición", "Editorial", "Lugar" ,"Fecha de edición"
        };
        modelo.setColumnIdentifiers(cabecera);
        tblLibros.setModel(modelo);

    }

    public void setDatos() {
        Object[] Datosfila = new Object[modelo.getColumnCount()];
        int nro = 1;
        for (PersonaModelo datos : listaLibroModelo ) {
            Datosfila[0] = nro;
            Datosfila[1] = datos.getTitulo();
            Datosfila[2] = datos.getAutor();
            Datosfila[3] = datos.getISBN();
            Datosfila[4] = datos.getPáginas();
            Datosfila[5] = datos.getEdición();
            Datosfila[6] = datos.getEditorial();
            Datosfila[7] = datos.getLugar();
            Datosfila[8] = datos.getFecha();
            nro++;
            modelo.addRow(Datosfila);

        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        lblIsbn = new javax.swing.JLabel();
        lblPagina = new javax.swing.JLabel();
        lblEdicion = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        txtIsbn = new javax.swing.JTextField();
        txtpagina = new javax.swing.JTextField();
        txtedicion = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibros = new javax.swing.JTable();
        btnInsertar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        tbnListar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblLugar = new javax.swing.JLabel();
        lblFEdicion = new javax.swing.JLabel();
        txtlugar = new javax.swing.JTextField();
        lblEditorial = new javax.swing.JLabel();
        txtEditorial = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        txtFechaE = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestor de libros ");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo.setText("Titulo");

        lblAutor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAutor.setText("Autor");

        lblIsbn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIsbn.setText("ISBN");

        lblPagina.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPagina.setText("Pagina");

        lblEdicion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEdicion.setText("Edicion");

        tblLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLibros);

        btnInsertar.setText("Insertar Tabla");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tbnListar.setText("Listar");
        tbnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnListarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblLugar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLugar.setText("Lugar");

        lblFEdicion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFEdicion.setText("Fecha edición");

        lblEditorial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEditorial.setText("Editorial");

        btnModificar.setText("Modificar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPagina)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEdicion)
                                    .addComponent(lblIsbn)
                                    .addComponent(lblAutor)
                                    .addComponent(lblTitulo)
                                    .addComponent(lblFEdicion)
                                    .addComponent(lblEditorial)
                                    .addComponent(lblLugar))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtlugar, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAutor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIsbn, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtpagina, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtedicion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEditorial)
                                    .addComponent(txtFechaE, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(305, 305, 305)
                                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(304, 304, 304)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnInsertar)
                                            .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tbnListar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(216, 216, 216))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAutor)
                            .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIsbn)
                            .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPagina)
                            .addComponent(txtpagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEdicion)
                            .addComponent(txtedicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEditorial)
                            .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLugar)
                            .addComponent(txtlugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFEdicion)
                            .addComponent(txtFechaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnInsertar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(tbnListar)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
    String autor = txtAutor.getText();
    String titulo =txtTitulo.getText();
    String ISBN = txtIsbn.getText();
    int paginas = Integer.parseInt(txtpagina.getText());
    String edición= txtedicion.getText();
    String editorial = txtEditorial.getText();
    String lugar = txtlugar.getText(); 
    String fecha = txtFechaE.getText();
        

        // Crear una instancia de PersonaModelo con los datos obtenidos
        PersonaModelo nuevaPersona = new PersonaModelo(autor,titulo,ISBN,paginas,edición,editorial,lugar, fecha);

        // Crear una instancia de PersonaControlador
        PersonaControlador controlador = new PersonaControlador();

        // Llamar al método crearPersona
        //controlador.crearPersona(nuevaPersona);
        setDatos();
        //limpiarTabla();
        //cargarTabla();
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
               // Obtener la cédula del campo de texto
        String titulo = txtTitulo.getText();

        // Crear una instancia de PersonaModelo con la cédula
        PersonaModelo personaBuscada = new PersonaModelo();
        personaBuscada.setTitulo(titulo);

        // Crear una instancia de PersonaControlador
        PersonaControlador controlador = new PersonaControlador();

        // Llamar al método recuperarDatosPersona
        //controlador.recuperarDatosPersona(personaBuscada);

        // Limpiar la tabla
        //limpiarTabla();

        // Agregar la persona buscada a la lista de personas
        listaLibroModelo.clear();
        listaLibroModelo.add(personaBuscada);

        // Llamar al método setDatos para agregar las personas a la tabla
        setDatos();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tbnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnListarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbnListarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
       limpiarEntradas();
    }//GEN-LAST:event_btnEliminarActionPerformed

     public void limpiarTabla() {
        int a = modelo.getRowCount() - 1;

        for (int i = a; i >= 0; i--) {

            modelo.removeRow(i);
        }
    }

    public void limpiarEntradas() {
        txtTitulo.setText("");
        txtAutor.setText("");
        txtIsbn.setText("");
        txtpagina.setText("");
        txtedicion.setText("");
        txtEditorial.setText("");
        
    }

    private void cargarTabla() {
        PersonaControlador pC = new PersonaControlador();
        ArrayList<Object[]> listaP = pC.datosPersona;
        for (Object[] fila : listaP) {
            modelo.addRow(fila);
        }
        tblLibros.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblEdicion;
    private javax.swing.JLabel lblEditorial;
    private javax.swing.JLabel lblFEdicion;
    private javax.swing.JLabel lblIsbn;
    private javax.swing.JLabel lblLugar;
    private javax.swing.JLabel lblPagina;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblLibros;
    private javax.swing.JButton tbnListar;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtFechaE;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtedicion;
    private javax.swing.JTextField txtlugar;
    private javax.swing.JTextField txtpagina;
    // End of variables declaration//GEN-END:variables
}
